### ISSUE TITLE
OnLogMessage Assumes "Fatal" If Exception Passed In.

### ISSUE THREAD

**Issue by GuyWaguespack** [SynapseProject/synapse.core.net#78]
OnLogMessage logs the message as "Fatal" if an exception is passed into the method, even if a different LogLevel is provided.   This might not be a valid assumption.

**Comment by steveshortt** [comment]
The issue with assuming Fatal is actually in the `LogMessageEventArgs` ctor, not the event method.  However, since the method definition in `HandlerRuntimeBase` is `protected virtual', just override it and be sure to call `LogMessage?.Invoke( this, args );`, where args a properly constructed `LogMessageEventArgs` instance.

```java
        protected virtual void OnLogMessage(string context, string message, LogLevel level = LogLevel.Info, Exception ex = null)
        {
            LogMessageEventArgs args = new LogMessageEventArgs( context, message, level, ex );
            LogMessage?.Invoke( this, args );
        }
```
